<?php 
	echo $this->doctype(); 
	/** @var \UIComponents\View\Helper\Utilities $oUtilities **/
	$oUtilities = $this->Utilities();
	/** @var \UIComponents\View\Helper\Components $oComponents **/
	$oComponents = $this->Components();
?>
<html class="no-js css-menubar" lang="<?php echo \Locale::getPrimaryLanguage(null) ?>">
	<head>
		<!-- <?php echo __DIR__ ; ?> -->
		<meta charset="utf-8">
		<?php echo $this->headTitle('[BB] '. $this->translate($oUtilities->AppTitle()))->setSeparator(' - ')->setAutoEscape(false) ?>
		<?php 
			echo $this->headMeta()
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
				->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui')
				->appendName('description', 'ZF2 Base Application')
				->appendName('author', '[drgon-projecs.net]')
			;
		?>
	
		<?php 
			$themePath = "themes/remark/assets/";
			$this->headLink(array(
					'rel' => 'shortcut icon', 
					'type' => 'image/vnd.microsoft.icon', 
					'href' => $this->basePath($themePath . $oUtilities->AppFavicon())
	 			))
	 			->append((object)array(
					'rel' => 'apple-touch-icon', 
					'href' => $this->basePath($themePath . 'images/apple-touch-icon.png')
	 			))
			;
			$this->headLink()
				->appendStylesheet($this->basePath($themePath . 'css/stylesheets.css'))
				->appendStylesheet($this->basePath($themePath . 'css/fontawesome/css/font-awesome.min.css'))
				->appendStylesheet($this->basePath($themePath . 'vendor/datatables/dataTables.min.css'))
				->appendStylesheet($this->basePath($themePath . 'vendor/datatables-bootstrap/dataTables.bootstrap.min.css'))
				->appendStylesheet($this->basePath($themePath . 'vendor/datatables-responsive/dataTables.responsive.min.css'))
				//->appendStylesheet($this->basePath($themePath . '../../basic/assets/js/datatables/css/dataTables.bootstrap.min.css'))
				
				->appendStylesheet($this->basePath('application-assets/dist/myapplication.min.css'))
			;
			$cssfiles = $oUtilities->Config()->get('app')->get('css');
			if (is_array($cssfiles) || ($cssfiles instanceof \Zend\Config\Config)) foreach ($cssfiles as $key => $file) {
				$this->headLink()->appendStylesheet($this->basePath($file));
			}
			echo $this->headLink();
		?>
	
		<?php 
			$this->headScript()
				->appendFile($this->basePath($themePath . 'vendor/html5shiv//html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
				->appendFile($this->basePath($themePath . 'vendor/media-match/media.match.min.js'), 'text/javascript', array('conditional' => 'lt IE 10',))
				->appendFile($this->basePath($themePath . 'vendor/respond/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 10',))
				->appendFile($this->basePath($themePath . 'vendor/modernizr/modernizr.js'), 'text/javascript')
				->appendFile($this->basePath($themePath . 'vendor/breakpoints/breakpoints.js'), 'text/javascript')
			;
			echo $this->headScript();
			echo $this->inlineScript('SCRIPT', 'Breakpoints();');
		?>
	</head>
	<body class="dashboard">
		<!--[if lt IE 8]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
	
		<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
	
			<div class="navbar-header">
				<button type="button" class="navbar-toggle hamburger hamburger-close navbar-toggle-left hided" data-toggle="menubar">
					<span class="sr-only">Toggle navigation</span>
					<span class="hamburger-bar"></span>
				</button>
				<button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-collapse" data-toggle="collapse">
					<i class="icon wb-more-horizontal" aria-hidden="true"></i>
				</button>
				<div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
					<img class="navbar-brand-logo" src="<?php echo $this->basePath($themePath.$oUtilities->AppLogo()) ?>" title="<?php echo $oUtilities->AppTitle(); ?>">
					<span class="navbar-brand-text"> <?php echo $this->translate($oUtilities->AppTitle()) ?></span>
				</div>
				<button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-search" data-toggle="collapse">
					<span class="sr-only">Toggle Search</span>
					<i class="icon wb-search" aria-hidden="true"></i>
				</button>
			</div>
		
			<div class="navbar-container container-fluid">
				<!-- Navbar Collapse -->
				<div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
					<!-- Navbar Toolbar -->
					<?php echo $this->partial('partial/navbar-toolbar.phtml', array("themePath" => $themePath)); ?>
					<!-- End Navbar Toolbar -->
			
					<!-- Navbar Toolbar Right -->
					<?php echo $this->partial('partial/navbar-toolbar-right.phtml', array("themePath" => $themePath)); ?>
					<?php 
						$oLocaleMenu = $oComponents->Languagemenu()
							->setUlClass('nav navbar-toolbar navbar-right navbar-toolbar-right')
							->setIconPrefixClass('flag-icon flag-icon-')
						;
						echo $oLocaleMenu->render(); 
					?>
					<!-- End Navbar Toolbar Right -->
				</div>
				<!-- End Navbar Collapse -->
		
				<!-- Site Navbar Seach -->
				<div class="collapse navbar-search-overlap" id="site-navbar-search">
				<form role="search">
					<div class="form-group">
					<div class="input-search">
						<i class="input-search-icon wb-search" aria-hidden="true"></i>
						<input type="text" class="form-control" name="site-search" placeholder="Search...">
						<button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
						data-toggle="collapse" aria-label="Close"></button>
					</div>
					</div>
				</form>
				</div>
				<!-- End Site Navbar Seach -->
			</div>
		</nav>
		
		<div class="site-menubar">
			<div class="site-menubar-body">
				<div>
					<div>
			
						<?php 
							$oNavBar = $oComponents->Nav('navigation')
								  ->setMinDepth(0)
								  ->setMaxDepth(3)
								  ->setUlClass('site-menu')
								  ->setSubUlClass('site-menu-sub')
								  ->setSubUlClassLevel1('site-menu-sub')
								  ->setDefaultLiClass('site-menu-item')
								  ->setSubLiClass('site-menu-item has-sub')
								  ->setSubLiClassLevel0('site-menu-item has-sub')
								  ->setLiActiveClass('active open')
								  ->setIconPrefixClass('site-menu-icon fa fa-')
								  //->setIconPrefixClass('site-menu-icon wb-')
						  		  ->setHrefSubToggleOverride('javascript:void(0);')
							;
							echo $oNavBar->render();
						?>
						
						<div class="site-menubar-section">
							<h5>
								Milestone
								<span class="pull-right">30%</span>
							</h5>
							<div class="progress progress-xs">
								<div class="progress-bar active" style="width: 30%;" role="progressbar"></div>
							</div>
							<h5>
								Release
								<span class="pull-right">60%</span>
							</h5>
							<div class="progress progress-xs">
								<div class="progress-bar progress-bar-warning" style="width: 60%;" role="progressbar"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		
			<div class="site-menubar-footer">
				<a href="javascript: void(0);" class="fold-show" data-placement="top" data-toggle="tooltip" data-original-title="Settings">
					<span class="icon wb-settings" aria-hidden="true"></span>
				</a>
				<a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Lock">
					<span class="icon wb-eye-close" aria-hidden="true"></span>
				</a>
				<a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Logout">
					<span class="icon wb-power" aria-hidden="true"></span>
				</a>
			</div>
		</div>
		<div class="site-gridmenu">
			<div>
				<div>
					<ul>
						<li>
							<a href="apps/mailbox/mailbox.html">
								<i class="icon wb-envelope"></i>
								<span>Mailbox</span>
							</a>
						</li>
						<li>
							<a href="apps/calendar/calendar.html">
								<i class="icon wb-calendar"></i>
								<span>Calendar</span>
							</a>
						</li>
						<li>
							<a href="apps/contacts/contacts.html">
								<i class="icon wb-user"></i>
								<span>Contacts</span>
							</a>
						</li>
						<li>
							<a href="apps/media/overview.html">
								<i class="icon wb-camera"></i>
								<span>Media</span>
							</a>
						</li>
						<li>
							<a href="apps/documents/categories.html">
								<i class="icon wb-order"></i>
								<span>Documents</span>
							</a>
						</li>
						<li>
							<a href="apps/projects/projects.html">
								<i class="icon wb-image"></i>
								<span>Project</span>
							</a>
						</li>
						<li>
							<a href="apps/forum/forum.html">
								<i class="icon wb-chat-group"></i>
								<span>Forum</span>
							</a>
						</li>
						<li>
							<a href="index.html">
								<i class="icon wb-dashboard"></i>
								<span>Dashboard</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	
	
		<!-- Page -->
		<div class="page">
			<div class="page-header padding-15">
				<h1 class="page-title margin-bottom-10"><?php echo $this->escapeHtml((isset($this->title) ? $this->title : "")); ?></h1>
				<?php 
					$oBreadcrumbs = $oComponents->Breadcrumbs('navigation')
						//->setHeader( $this->translate('you are here :') )
						->setMinDepth(0)
					;
					echo $oBreadcrumbs->render(); 
				?>
			</div>
			
			<div class="page-content padding-15 container-fluid">
			
				<div id="panel-messages" class="row">					
					<div class="col-md-12">		
						<?php
							echo $this->flashMessenger()->render('error', array('alert alert-error alert-dismissible dark flashmessages'));
							echo $this->flashMessenger()->render('warning', array('alert alert-warning alert-dismissible dark flashmessages'));
							echo $this->flashMessenger()->render('success', array('alert alert-success alert-dismissible dark flashmessages'));
							echo $this->flashMessenger()->render('info', array('alert alert-info alert-dismissible dark flashmessages'));
						?>
					</div>
				</div>
					
				<?php
					/*$params = $this->getHelperPluginManager()
						->getServiceLocator()
						->get('Application')
						->getMvcEvent()
						->getRouteMatch()
						->getParams();*/
					//if ($params["action"] == "index") {
						//echo $this->content;
					//} else {
						$panelLayout = $oComponents->Panel()
						//->setHeader( (isset($this->title) ? $this->title : "") )
						->setContent(
								array(
										'tagname' => 'div',
										'classnames' => 'panel-body alert-wrap',
										'content' => $this->content,
								)
							)
						;
						
						echo $panelLayout;
					//}
				?>
				
			</div>
		</div>
		<!-- End Page -->
	
	
		<!-- Footer -->
		<footer class="site-footer">
			<span class="site-footer-legal">
				<span class="copyright">&copy; <?php echo date('Y') ?> by <a href="//dragon-projects.net" target="_blank">[dragon-projects.net]</a> - <?php echo $this->translate('All rights reserved.') ?></span>
			</span>
			<div class="site-footer-right">
				<span class="poweredby">
					<?php echo $this->translate('Powered by') ?> &nbsp;
					<a href="http://php.net" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/php-logo.gif') ?>" height="20" alt="php" /></a> &nbsp;
					<a href="http://framework.zend.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/zf2-logo.png') ?>" height="16" alt="ZendFramework 2" /></a> &nbsp;
					<a href="http://www.w3.org/html/" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/html5-badge-h-solo.png') ?>" height="16" alt="HTML5" /></a> &nbsp;
					<a href="http://jquery.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/jquery-logo.png') ?>" height="16" alt="jQuery" /></a>
				</span>
			</div>
		</footer>
		<?php 
			$this->inlineScript()
		
		// <!-- Core	-->
				->appendFile($this->basePath($themePath . 'vendor/jquery/jquery.js'))
				->appendFile($this->basePath($themePath . 'vendor/bootstrap/bootstrap.js'))
				->appendFile($this->basePath($themePath . 'vendor/animsition/jquery.animsition.js'))
				->appendFile($this->basePath($themePath . 'vendor/asscroll/jquery-asScroll.js'))
				->appendFile($this->basePath($themePath . 'vendor/mousewheel/jquery.mousewheel.js'))
				->appendFile($this->basePath($themePath . 'vendor/asscrollable/jquery.asScrollable.all.js'))
				->appendFile($this->basePath($themePath . 'vendor/ashoverscroll/jquery-asHoverScroll.js'))
	
		// <!-- Plugins -->
				->appendFile($this->basePath($themePath . 'vendor/switchery/switchery.min.js'))
				->appendFile($this->basePath($themePath . 'vendor/intro-js/intro.js'))
				->appendFile($this->basePath($themePath . 'vendor/screenfull/screenfull.js'))
				->appendFile($this->basePath($themePath . 'vendor/slidepanel/jquery-slidePanel.js'))
			
				->appendFile($this->basePath($themePath . '../../basic/assets/js/datatables/js/jquery.dataTables.min.js'))
	
		// <!-- Plugins For This Page -->
				->appendFile($this->basePath($themePath . 'vendor/skycons/skycons.js'))
				//->appendFile($this->basePath($themePath . 'vendor/chartist-js/chartist.min.js'))
				//->appendFile($this->basePath($themePath . 'vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.min.js'))
				//->appendFile($this->basePath($themePath . 'vendor/aspieprogress/jquery-asPieProgress.min.js'))
				//->appendFile($this->basePath($themePath . 'vendor/jvectormap/jquery-jvectormap.min.js'))
				//->appendFile($this->basePath($themePath . 'vendor/jvectormap/maps/jquery-jvectormap-au-mill-en.js'))
				->appendFile($this->basePath($themePath . 'vendor/matchheight/jquery.matchHeight-min.js'))
	
		// <!-- Scripts -->
				->appendFile($this->basePath($themePath . 'js/core.js'))
				->appendFile($this->basePath($themePath . 'js/site.js'))
	
				->appendFile($this->basePath($themePath . 'js/sections/menu.js'))
				->appendFile($this->basePath($themePath . 'js/sections/menubar.js'))
				->appendFile($this->basePath($themePath . 'js/sections/gridmenu.js'))
				->appendFile($this->basePath($themePath . 'js/sections/sidebar.js'))
	
				->appendFile($this->basePath($themePath . 'js/configs/config-colors.js'))
				->appendFile($this->basePath($themePath . 'js/configs/config-tour.js'))
	
				->appendFile($this->basePath($themePath . 'js/components/asscrollable.js'))
				->appendFile($this->basePath($themePath . 'js/components/animsition.js'))
				->appendFile($this->basePath($themePath . 'js/components/slidepanel.js'))
				->appendFile($this->basePath($themePath . 'js/components/switchery.js'))
	
		// <!-- Scripts For This Page -->
				->appendFile($this->basePath($themePath . 'js/components/matchheight.js'))
				->appendFile($this->basePath($themePath . 'js/components/jvectormap.js'))


				->appendFile($this->basePath('application-assets/dist/myapplication.min.js'))
	
				->appendFile($this->basePath($themePath . 'examples/js/dashboard/v1.js'))
			;
			$jsfiles = $oUtilities->Config()->get('app')->get('js');
			if (is_array($jsfiles) || ($jsfiles instanceof \Zend\Config\Config)) foreach ($jsfiles as $key => $file) {
				$this->inlineScript()->appendFile($this->basePath($file));
			}
			echo $this->inlineScript();
		?>
	</body>
</html>