<?php echo $this->doctype(); ?>
<html class="no-js css-menubar" lang="en">
<head>
	<!-- <?php echo __DIR__ ; ?> -->
	<meta charset="utf-8">
	<?php echo $this->headTitle('[BB] '. $this->translate('MyApplication'))->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php 
		echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui')
			->appendName('description', 'ZF2 Base Application')
			->appendName('author', '[drgon-projecs.net]')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		;
	?>

	<?php 
		$themePath = "assets/themes/remark/";
		$this->headLink(array(
				'rel' => 'shortcut icon', 
				'type' => 'image/vnd.microsoft.icon', 
				'href' => $this->basePath($themePath . 'images/favicon.ico')
 			))
 			->append((object)array(
				'rel' => 'apple-touch-icon', 
				'href' => $this->basePath($themePath . 'images/apple-touch-icon.png')
 			))
		;
		$this->headLink()
			->appendStylesheet($this->basePath($themePath . 'css/stylesheets.css'))
		;
		echo $this->headLink();
	?>

	<?php 
		$this->headScript()
			->appendFile($this->basePath($themePath . 'vendor/html5shiv//html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
			->appendFile($this->basePath($themePath . 'vendor/media-match/media.match.min.js'), 'text/javascript', array('conditional' => 'lt IE 10',))
			->appendFile($this->basePath($themePath . 'vendor/respond/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 10',))
			->appendFile($this->basePath($themePath . 'vendor/modernizr/modernizr.js'), 'text/javascript')
			->appendFile($this->basePath($themePath . 'vendor/breakpoints/breakpoints.js'), 'text/javascript')
		;
		echo $this->headScript();
		echo $this->inlineScript('SCRIPT', 'Breakpoints();');
	?>
</head>
<body class="dashboard">
	<!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->

	<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">

		<div class="navbar-header">
			<button type="button" class="navbar-toggle hamburger hamburger-close navbar-toggle-left hided"
			data-toggle="menubar">
				<span class="sr-only">Toggle navigation</span>
				<span class="hamburger-bar"></span>
			</button>
			<button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-collapse"
			data-toggle="collapse">
				<i class="icon wb-more-horizontal" aria-hidden="true"></i>
			</button>
			<div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
			<img class="navbar-brand-logo" src="<?php echo $themePath; ?>images/logo.png" title="Remark">
			<span class="navbar-brand-text"> Remark</span>
			</div>
			<button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-search"
			data-toggle="collapse">
			<span class="sr-only">Toggle Search</span>
			<i class="icon wb-search" aria-hidden="true"></i>
			</button>
		</div>
	
		<div class="navbar-container container-fluid">
			<!-- Navbar Collapse -->
			<div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
			<!-- Navbar Toolbar -->
			<?php include __DIR__."/../partial/navbar-toolbar.phtml"; ?>
			<!-- End Navbar Toolbar -->
	
			<!-- Navbar Toolbar Right -->
			<?php include __DIR__."/../partial/navbar-toolbar-right.phtml"; ?>
			<!-- End Navbar Toolbar Right -->
			</div>
			<!-- End Navbar Collapse -->
	
			<!-- Site Navbar Seach -->
			<div class="collapse navbar-search-overlap" id="site-navbar-search">
			<form role="search">
				<div class="form-group">
				<div class="input-search">
					<i class="input-search-icon wb-search" aria-hidden="true"></i>
					<input type="text" class="form-control" name="site-search" placeholder="Search...">
					<button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
					data-toggle="collapse" aria-label="Close"></button>
				</div>
				</div>
			</form>
			</div>
			<!-- End Site Navbar Seach -->
		</div>
	</nav>
	
	<div class="site-menubar">
	<div class="site-menubar-body">
		<div>
		<div>

			<?php require __DIR__."/../partial/site-menu.phtml"; ?>
			
			<div class="site-menubar-section">
			<h5>
				Milestone
				<span class="pull-right">30%</span>
			</h5>
			<div class="progress progress-xs">
				<div class="progress-bar active" style="width: 30%;" role="progressbar"></div>
			</div>
			<h5>
				Release
				<span class="pull-right">60%</span>
			</h5>
			<div class="progress progress-xs">
				<div class="progress-bar progress-bar-warning" style="width: 60%;" role="progressbar"></div>
			</div>
			</div>
		</div>
		</div>
	</div>

	<div class="site-menubar-footer">
		<a href="javascript: void(0);" class="fold-show" data-placement="top" data-toggle="tooltip"
		data-original-title="Settings">
		<span class="icon wb-settings" aria-hidden="true"></span>
		</a>
		<a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Lock">
		<span class="icon wb-eye-close" aria-hidden="true"></span>
		</a>
		<a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Logout">
		<span class="icon wb-power" aria-hidden="true"></span>
		</a>
	</div>
	</div>
	<div class="site-gridmenu">
	<div>
		<div>
		<ul>
			<li>
			<a href="apps/mailbox/mailbox.html">
				<i class="icon wb-envelope"></i>
				<span>Mailbox</span>
			</a>
			</li>
			<li>
			<a href="apps/calendar/calendar.html">
				<i class="icon wb-calendar"></i>
				<span>Calendar</span>
			</a>
			</li>
			<li>
			<a href="apps/contacts/contacts.html">
				<i class="icon wb-user"></i>
				<span>Contacts</span>
			</a>
			</li>
			<li>
			<a href="apps/media/overview.html">
				<i class="icon wb-camera"></i>
				<span>Media</span>
			</a>
			</li>
			<li>
			<a href="apps/documents/categories.html">
				<i class="icon wb-order"></i>
				<span>Documents</span>
			</a>
			</li>
			<li>
			<a href="apps/projects/projects.html">
				<i class="icon wb-image"></i>
				<span>Project</span>
			</a>
			</li>
			<li>
			<a href="apps/forum/forum.html">
				<i class="icon wb-chat-group"></i>
				<span>Forum</span>
			</a>
			</li>
			<li>
			<a href="index.html">
				<i class="icon wb-dashboard"></i>
				<span>Dashboard</span>
			</a>
			</li>
		</ul>
		</div>
	</div>
	</div>


	<!-- Page -->
	<div class="page">
	<div class="page-content padding-30 container-fluid">
		<div class="row" data-plugin="matchHeight" data-by-row="true">
		<div class="col-xlg-7 col-md-7">
			<!-- Widget Linearea Color -->
			<div class="widget widget-shadow widget-responsive" id="widgetLineareaColor">
			<div class="widget-content">
				<div class="padding-top-30 padding-30" style="height:calc(100% - 250px);">
				<div class="row">
					<div class="col-xs-7">
					<p class="font-size-20 blue-grey-700">Eneergy Predictions</p>
					<p>Quisque volutpat condimentum velit. Class aptent taciti</p>
					<div class="counter counter-md text-left">
						<div class="counter-number-group">
						<span class="counter-icon red-600"><i class="icon wb-triangle-up" aria-hidden="true"></i></span>
						<span class="counter-number red-600">2,250</span>
						</div>
					</div>
					</div>
					<div class="col-xs-5">
					<div class="pull-right clearfix">
						<ul class="list-unstyled">
						<li class="margin-bottom-5 text-truncate">
							<i class="icon wb-medium-point red-600 margin-right-5" aria-hidden="true"></i>							Diretary intake
						</li>
						<li class="margin-bottom-5 text-truncate">
							<i class="icon wb-medium-point orange-600 margin-right-5" aria-hidden="true"></i>							Motion
						</li>
						<li class="margin-bottom-5 text-truncate">
							<i class="icon wb-medium-point green-600 margin-right-5" aria-hidden="true"></i>							Other
						</li>
						</ul>
					</div>
					</div>
				</div>
				</div>
				<div class="ct-chart height-250"></div>
			</div>
			</div>
			<!-- End Widget Linearea Color -->
		</div>

		<div class="col-xlg-5 col-md-5">
			<!-- Widget Stacked Bar -->
			<div class="widget widget-shadow" id="widgetStackedBar">
			<div class="widget-content">
				<div class="padding-30 height-150">
				<p>MARKET DOW</p>
				<div class="red-600">
					<i class="wb-triangle-up font-size-20 margin-right-5"></i>
					<span class="font-size-30">26,580.62</span>
				</div>
				</div>
				<div class="counters padding-bottom-20 padding-horizontal-30" style="height:calc(100% - 350px);">
				<div class="row no-space">
					<div class="col-xs-4">
					<div class="counter counter-sm">
						<div class="counter-label text-uppercase">APPL</div>
						<div class="counter-number-group text-truncate">
						<span class="counter-number-related green-600">+</span>
						<span class="counter-number green-600">82.24</span>
						<span class="counter-number-related green-600">%</span>
						</div>
					</div>
					</div>
					<div class="col-xs-4">
					<div class="counter counter-sm">
						<div class="counter-label text-uppercase">FB</div>
						<div class="counter-number-group text-truncate">
						<span class="counter-number-related red-600">-</span>
						<span class="counter-number red-600">12.06</span>
						<span class="counter-number-related red-600">%</span>
						</div>
					</div>
					</div>
					<div class="col-xs-4">
					<div class="counter counter-sm">
						<div class="counter-label text-uppercase">GOOG</div>
						<div class="counter-number-group text-truncate">
						<span class="counter-number-related green-600">+</span>
						<span class="counter-number green-600">24.86</span>
						<span class="counter-number-related green-600">%</span>
						</div>
					</div>
					</div>
				</div>
				</div>
				<div class="ct-chart height-200"></div>
			</div>
			</div>
			<!-- End Widget Stacked Bar -->
		</div>

		<div class="col-xlg-8 col-md-12">
			<!-- Widget Statistic -->
			<div class="widget widget-shadow" id="widgetStatistic">
			<div class="widget-content">
				<div class="row no-space height-full" data-plugin="matchHeight">
				<div class="col-sm-8 col-xs-12">
					<div id="widgetJvmap" class="height-full"></div>
				</div>
				<div class="col-sm-4 col-xs-12 padding-30">
					<div class="form-group">
					<div class="input-search input-search-dark">
						<i class="input-search-icon wb-search" aria-hidden="true"></i>
						<input type="text" class="form-control" name="" placeholder="Search...">
					</div>
					</div>
					<p class="font-size-20 blue-grey-700">Statistic</p>
					<p class="blue-grey-400">Status: live</p>
					<p>
					<i class="icon wb-map blue-grey-400 margin-right-10" aria-hidden="true"></i>
					<span>258 Countries, 4835 Cities</span>
					</p>
					<ul class="list-unstyled margin-top-20">
					<li>
						<p>VISITS</p>
						<div class="progress progress-xs margin-bottom-25">
						<div class="progress-bar progress-bar-info bg-blue-600" style="width: 70.3%" aria-valuemax="100"
						aria-valuemin="0" aria-valuenow="70.3" role="progressbar">
							<span class="sr-only">70.3%</span>
						</div>
						</div>
					</li>
					<li>
						<p>TODAY</p>
						<div class="progress progress-xs margin-bottom-25">
						<div class="progress-bar progress-bar-info bg-green-600" style="width: 70.3%" aria-valuemax="100"
						aria-valuemin="0" aria-valuenow="70.3" role="progressbar">
							<span class="sr-only">70.3%</span>
						</div>
						</div>
					</li>
					<li>
						<p>WEEK</p>
						<div class="progress progress-xs margin-bottom-0">
						<div class="progress-bar progress-bar-info bg-purple-600" style="width: 70.3%"
						aria-valuemax="100" aria-valuemin="0" aria-valuenow="70.3"
						role="progressbar">
							<span class="sr-only">70.3%</span>
						</div>
						</div>
					</li>
					</ul>
				</div>
				</div>
			</div>
			</div>
			<!-- End Widget Statistic -->
		</div>

		<div class="col-xlg-4 col-md-12">
			<div class="row height-full">
			<div class="col-xlg-12 col-md-6" style="height:50%;">
				<!-- Widget Linepoint -->
				<div class="widget widget-shadow bg-blue-600 white" id="widgetLinepoint">
				<div class="widget-content">
					<div class="padding-top-25 padding-horizontal-30">
					<div class="row no-space">
						<div class="col-xs-6">
						<p>Today Sale's</p>
						<p class="blue-200">Last Sale 23.45 USD</p>
						</div>
						<div class="col-xs-6 text-right">
						<p class="font-size-30 text-nowrap">450 USD</p>
						</div>
					</div>
					</div>
					<div class="ct-chart height-120"></div>
				</div>
				</div>
				<!-- End Widget Linepoint -->
			</div>
			<div class="col-xlg-12 col-md-6" style="height:50%;">
				<!-- Widget Sale Bar -->
				<div class="widget widget-shadow bg-purple-600 white" id="widgetSaleBar">
				<div class="widget-content">
					<div class="padding-top-25 padding-horizontal-30">
					<div class="row no-space">
						<div class="col-xs-6">
						<p>Month Sale's</p>
						<p class="purple-200">2% higher than last month</p>
						</div>
						<div class="col-xs-6 text-right">
						<p class="font-size-30 text-nowrap">$ 14,500</p>
						</div>
					</div>
					</div>
					<div class="ct-chart height-120"></div>
				</div>
				</div>
				<!-- End Widget Sale Bar -->
			</div>
			</div>
		</div>

		<div class="col-xlg-6 col-md-12">
			<!-- Widget OVERALL VIEWS -->
			<div class="widget widget-shadow widget-responsive" id="widgetOverallViews">
			<div class="widget-content padding-30">
				<div class="row padding-bottom-30" style="height:calc(100% - 250px);">
				<div class="col-xs-4">
					<div class="counter counter-md text-left">
					<div class="counter-label">OVERALL VIEWS</div>
					<div class="counter-number-group text-truncate">
						<span class="counter-number-related red-600">$</span>
						<span class="counter-number red-600">432,852</span>
					</div>
					<div class="counter-label">2% higher than last month</div>
					</div>
				</div>
				<div class="col-xs-4">
					<div class="counter counter-sm text-left inline-block">
					<div class="counter-label">MY BALANCE</div>
					<div class="counter-number-group">
						<span class="counter-number-related">$</span>
						<span class="counter-number">12,346</span>
					</div>
					</div>
					<div class="ct-chart inline-block small-bar-one"></div>
				</div>
				<div class="col-xs-4">
					<div class="counter counter-sm text-left inline-block">
					<div class="counter-label">NEW ORDERS</div>
					<div class="counter-number-group">
						<span class="counter-number-related">$</span>
						<span class="counter-number">17,555</span>
					</div>
					</div>
					<div class="ct-chart inline-block small-bar-two"></div>
				</div>
				</div>
				<div class="ct-chart line-chart height-250"></div>
			</div>
			</div>
			<!-- End Widget OVERALL VIEWS -->
		</div>

		<div class="col-xlg-6 col-md-12">
			<!-- Widget Timeline -->
			<div class="widget widget-shadow widget-responsive" id="widgetTimeline">
			<div class="widget-content">
				<div class="padding-30" style="height:120px;">
				<div class="row">
					<div class="col-xs-4">
					<div class="counter text-left">
						<div class="counter-label blue-grey-700">Total usage</div>
						<div class="counter-number-group">
						<span class="counter-number red-600">21,451</span>
						<span class="counter-number-related red-600">MB</span>
						</div>
					</div>
					</div>
					<div class="col-xs-4">
					<div class="counter text-left">
						<div class="counter-label">Currently</div>
						<div class="counter-number-group">
						<span class="counter-number">227.34</span>
						<span class="counter-number-related">KB</span>
						</div>
					</div>
					</div>
					<div class="col-xs-4">
					<div class="counter text-left">
						<div class="counter-label">Average</div>
						<div class="counter-number-group">
						<span class="counter-number">117.65</span>
						<span class="counter-number-related">MB</span>
						</div>
					</div>
					</div>
				</div>
				</div>
				<ul class="list-unstyled padding-bottom-50" style="height:calc(100% - 270px);">
				<li class="padding-horizontal-30 padding-vertical-15 container-fluid">
					<div class="row">
					<div class="col-xs-3">Mail App</div>
					<div class="col-xs-6">210,685 users are using</div>
					<div class="col-xs-3 green-600">227.34KB</div>
					</div>
				</li>
				<li class="padding-horizontal-30 padding-vertical-15 container-fluid">
					<div class="row">
					<div class="col-xs-3">Calendar</div>
					<div class="col-xs-6">10,685 users are using</div>
					<div class="col-xs-3 green-600">128.62KB</div>
					</div>
				</li>
				</ul>
				<div class="ct-chart height-150"></div>
			</div>
			</div>
			<!-- End Widget Timeline -->
		</div>

		<div class="col-xlg-6 col-md-12">
			<!-- Panel California -->
			<div class="widget widget-shadow" id="widgetWeather">
			<div class="widget-content">
				<div class="row no-space height-full">
				<div class="col-sm-7 height-full">
					<div class="padding-35 text-center">
					<h4>California, Usa</h4>
					<p class="blue-grey-400 margin-bottom-35">MONDAY MAY 11, 2015</p>
					<canvas id="widgetSunny" height="60" width="60"></canvas>
					<div class="font-size-40 red-600">
						26°
						<span class="font-size-30">C</span>
					</div>
					<div>Sunday</div>
					</div>
					<div class="weather-times padding-30">
					<div class="row no-space text-center">
						<div class="col-xs-3">
						<div class="weather-day vertical-align">
							<div class="vertical-align-middle">
							<div class="margin-bottom-5">12:00</div>
							<i class="wi-day-cloudy font-size-24 margin-bottom-5"></i>
							<div class="red-600">24°
								<span class="font-size-12">C</span>
							</div>
							</div>
						</div>
						</div>
						<div class="col-xs-3">
						<div class="weather-day vertical-align">
							<div class="vertical-align-middle">
							<div class="margin-bottom-5">12:30</div>
							<i class="wi-day-sunny font-size-24 margin-bottom-5"></i>
							<div class="red-600">26°
								<span class="font-size-12">C</span>
							</div>
							</div>
						</div>
						</div>
						<div class="col-xs-3">
						<div class="weather-day vertical-align">
							<div class="vertical-align-middle">
							<div class="margin-bottom-5">13:00</div>
							<i class="wi-day-sunny font-size-24 margin-bottom-5"></i>
							<div class="red-600">28°
								<span class="font-size-12">C</span>
							</div>
							</div>
						</div>
						</div>
						<div class="col-xs-3">
						<div class="weather-day vertical-align">
							<div class="vertical-align-middle">
							<div class="margin-bottom-5">13:30</div>
							<i class="wi-day-sunny font-size-24 margin-bottom-5"></i>
							<div class="red-600">30°
								<span class="font-size-12">C</span>
							</div>
							</div>
						</div>
						</div>
					</div>
					</div>
				</div>
				<div class="col-sm-5 bg-blue-grey-100 height-full">
					<div class="weather-list">
					<ul class="list-unstyled margin-0">
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
						<li class="container-fluid">
						<div class="row no-space">
							<div class="col-xs-4">
							SUN
							</div>
							<div class="col-xs-4">
							<i class="wi-day-cloudy font-size-24"></i>
							</div>
							<div class="col-xs-4">
							24 - 26
							</div>
						</div>
						</li>
					</ul>
					</div>
				</div>
				</div>
			</div>
			</div>
			<!-- End Panel California -->
		</div>

		<div class="col-xlg-3 col-md-6">
			<!-- Panel Watchlist -->
			<div class="widget widget-shadow" id="widgetTable">
			<div class="widget-body padding-30">
				<h3 class="widget-title">
				<span class="text-truncate">Watch List</span>
				<span class="pull-right red-600 font-size-24">$ 102,967</span>
				</h3>
				<form class="margin-top-25" action="#" role="search">
				<div class="input-search input-search-dark">
					<i class="input-search-icon wb-search" aria-hidden="true"></i>
					<input type="text" class="form-control" placeholder="Search.." />
				</div>
				</form>
			</div>
			<table class="table margin-bottom-0">
				<tbody>
				<tr>
					<td>GMY</td>
					<td>$ 9,500</td>
					<td class="green-600">+ 458</td>
				</tr>
				<tr>
					<td>KPM</td>
					<td>$ 15,425</td>
					<td class="red-600">- 1,632</td>
				</tr>
				<tr>
					<td>PTR</td>
					<td>$ 11,540</td>
					<td class="green-600">+ 8,326</td>
				</tr>
				<tr>
					<td>HGM</td>
					<td>$ 15,855</td>
					<td class="green-600">+ 11,326</td>
				</tr>
				<tr>
					<td>MKR</td>
					<td>$ 18,500</td>
					<td class="red-600">- 6,586</td>
				</tr>
				</tbody>
			</table>
			</div>
			<!-- End Panel Watchlist -->
		</div>

		<div class="col-xlg-3 col-md-6">
			<!-- Widget Linepoint -->
			<div class="widget widget-shadow" id="widgetLinepointDate">
			<div class="widget-body padding-30">
				<h3 class="widget-title">Sales Analysis
				<span Class="label label-dark label-round pull-right">View</span>
				</h3>
				<div class="row text-center margin-vertical-25">
				<div class="col-xs-4">
					<div class="counter">
					<div class="counter-label">TOTAL</div>
					<div class="counter-number red-600">20,186</div>
					</div>
				</div>
				<div class="col-xs-4">
					<div class="counter">
					<div class="counter-label">TODAY</div>
					<div class="counter-number red-600">36</div>
					</div>
				</div>
				<div class="col-xs-4">
					<div class="counter">
					<div class="counter-label">WEEK</div>
					<div class="counter-number red-600">261</div>
					</div>
				</div>
				</div>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer
				nec odio. Praesent libero.</p>
			</div>
			<div class="ct-chart height-150"></div>
			</div>
			<!-- End Widget Linepoint -->
		</div>
		</div>
	</div>
	</div>
	<!-- End Page -->


	<!-- Footer -->
	<footer class="site-footer">
	<span class="site-footer-legal">© 2015 <a href="http://themeforest.net/item/remark-responsive-bootstrap-admin-template/11989202">Remark</a></span>
	<div class="site-footer-right">
		Crafted with <i class="red-600 wb wb-heart"></i> by <a href="http://themeforest.net/user/amazingSurge">amazingSurge</a>
	</div>
	</footer>
	<?php 
		$this->inlineScript()
	
	// <!-- Core	-->
			->appendFile($this->basePath($themePath . 'vendor/jquery/jquery.js'))
			->appendFile($this->basePath($themePath . 'vendor/bootstrap/bootstrap.js'))
			->appendFile($this->basePath($themePath . 'vendor/animsition/jquery.animsition.js'))
			->appendFile($this->basePath($themePath . 'vendor/asscroll/jquery-asScroll.js'))
			->appendFile($this->basePath($themePath . 'vendor/mousewheel/jquery.mousewheel.js'))
			->appendFile($this->basePath($themePath . 'vendor/asscrollable/jquery.asScrollable.all.js'))
			->appendFile($this->basePath($themePath . 'vendor/ashoverscroll/jquery-asHoverScroll.js'))

	// <!-- Plugins -->
			->appendFile($this->basePath($themePath . 'vendor/switchery/switchery.min.js'))
			->appendFile($this->basePath($themePath . 'vendor/intro-js/intro.js'))
			->appendFile($this->basePath($themePath . 'vendor/screenfull/screenfull.js'))
			->appendFile($this->basePath($themePath . 'vendor/slidepanel/jquery-slidePanel.js'))

	// <!-- Plugins For This Page -->
			->appendFile($this->basePath($themePath . 'vendor/skycons/skycons.js'))
			->appendFile($this->basePath($themePath . 'vendor/chartist-js/chartist.min.js'))
			->appendFile($this->basePath($themePath . 'vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.min.js'))
			->appendFile($this->basePath($themePath . 'vendor/aspieprogress/jquery-asPieProgress.min.js'))
			->appendFile($this->basePath($themePath . 'vendor/jvectormap/jquery-jvectormap.min.js'))
			->appendFile($this->basePath($themePath . 'vendor/jvectormap/maps/jquery-jvectormap-au-mill-en.js'))
			->appendFile($this->basePath($themePath . 'vendor/matchheight/jquery.matchHeight-min.js'))

	// <!-- Scripts -->
			->appendFile($this->basePath($themePath . 'js/core.js'))
			->appendFile($this->basePath($themePath . 'js/site.js'))

			->appendFile($this->basePath($themePath . 'js/sections/menu.js'))
			->appendFile($this->basePath($themePath . 'js/sections/menubar.js'))
			->appendFile($this->basePath($themePath . 'js/sections/gridmenu.js'))
			->appendFile($this->basePath($themePath . 'js/sections/sidebar.js'))

			->appendFile($this->basePath($themePath . 'js/configs/config-colors.js'))
			->appendFile($this->basePath($themePath . 'js/configs/config-tour.js'))

			->appendFile($this->basePath($themePath . 'js/components/asscrollable.js'))
			->appendFile($this->basePath($themePath . 'js/components/animsition.js'))
			->appendFile($this->basePath($themePath . 'js/components/slidepanel.js'))
			->appendFile($this->basePath($themePath . 'js/components/switchery.js'))

	// <!-- Scripts For This Page -->
			->appendFile($this->basePath($themePath . 'js/components/matchheight.js'))
			->appendFile($this->basePath($themePath . 'js/components/jvectormap.js'))

			->appendFile($this->basePath($themePath . 'examples/js/dashboard/v1.js'))
		;
		echo $this->inlineScript();
	?>
</body>

</html>